name: Build and Push new Image on Tag Creation

on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_IMAGE_NAME: frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          cd azure/app
          ls -l
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker build -f Dockerfile -t ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:${IMAGE_TAG} .
          docker push ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:${IMAGE_TAG}

