name: Build and Deploy to Testing

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  DOCKER_IMAGE_NAME: frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  deploy:
    name: Build, Push, and Deploy to Testing
    runs-on: ubuntu-latest
    environment: TEST  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Set commit hash as Docker tag
        id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          cd azure/app
          docker build -t martinus/${DOCKER_IMAGE_NAME}:${{ steps.vars.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push martinus/${DOCKER_IMAGE_NAME}:${{ steps.vars.outputs.tag }}

      - name: Deploy to Azure Web App (Testing)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_TESTING_NAME }}  # 👈 Using environment-scoped variable
          images: martinus/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.tag }}        

      - name: Summary
        run: |
          echo "### ✅ Deployed Successfully" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: **Testing**" >> $GITHUB_STEP_SUMMARY
          echo "- URL: [${{ vars.TESTING_URL }}](${{ vars.TESTING_URL }})" >> $GITHUB_STEP_SUMMARY
          echo "- Image: martinus/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.vars.outputs.tag }}" >> $GITHUB_STEP_SUMMARY