name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  DOCKER_IMAGE_NAME: frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_PRODUCTION_NAME }}
  PRODUCTION_URL: ${{ secrets.PRODUCTION_URL }}

jobs:
  deploy:
    name: Deploy to Production from DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Echo deployed URL
        run: echo "Deployed to production at $PRODUCTION_URL"