name: Build and Deploy to Testing

on:
  push:
    branches:
      - test
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  DOCKER_IMAGE_NAME: frontend
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_TESTING_NAME }}
  TESTING_URL: ${{ secrets.TESTING_URL }}

jobs:
  deploy:
    name: Build, Push, and Deploy to Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build Docker image
        run: |
          cd azure/app
          docker build -t ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:latest .

      - name: Push Docker image
        run: docker push ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:latest

      - name: Deploy to Azure Web App (Testing)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Echo deployed URL
        run: echo "Deployed to testing at $TESTING_URL"