name: Validate Azure Credentials

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  validate:
    name: Validate Azure Login
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Show current Azure account
        run: az account show
